logging:
  file: /var/log/galaxy/trade.log
  level.*: INFO
  level.io.terminus: DEBUG

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: cn.blmdz.wolf.(order|cart).model,cn.blmdz.rabbit.order.model

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/b2b2c?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  username: root
  password: root
  minimum-idle: 2
  connection-timeout: 5000

redis:
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

zookeeper:
  host: 127.0.0.1
  port: 2181

dubbo:
  name: galaxy-trade
  registry: zookeeper://127.0.0.1:2181
  port: -1
  timeout: 10000
  threads: 100
  heartBeats: 10000